name: Deploy to ECS (Final Working)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout
    - name: Checkout
      uses: actions/checkout@v4

    # 2. AWS credentials
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Login to ECR
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Build + Push image (UNIQUE VERSION)
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${{ github.sha }}
        IMAGE=${{ secrets.ECR_REPO_BACKEND }}:$IMAGE_TAG

        echo "Building image: $IMAGE"

        docker build --no-cache \
          --build-arg APP_VERSION=$IMAGE_TAG \
          -t $IMAGE ./backend

        docker push $IMAGE

        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    # 5. Install jq
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    # 6. Update Task Definition
    - name: Update ECS Task Definition
      run: |
        TASK_DEF=$(aws ecs describe-task-definition \
          --task-definition backend-task)

        NEW_TASK_DEF=$(echo $TASK_DEF | jq \
          --arg IMAGE "$IMAGE" \
          '.taskDefinition |
          .containerDefinitions[0].image = $IMAGE |
          del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )')

        echo "$NEW_TASK_DEF" > new-task-def.json

        aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json

    # 7. Deploy new revision
    - name: Deploy to ECS
      run: |
        REVISION=$(aws ecs describe-task-definition \
          --task-definition backend-task \
          --query 'taskDefinition.revision' \
          --output text)

        echo "Deploying revision: $REVISION"

        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.ECS_SERVICE }} \
          --task-definition backend-task:$REVISION
